service: testbed-test-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-north-1

functions:
  getPopulation:
    handler: testbed.getPopulation
    events:
      - httpApi:
          path: /getPopulation
          method: post

cors:
  - enabled: true
  - origin: https://testbed-test-front-bucket.s3.eu-north-1.amazonaws.com
  - headers: 'Content-Type,Authorization'
  - methods: 'POST'
plugins:
  - serverless-offline
