service: testbed-test-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-north-1
  httpApi:
    cors:
      allowedOrigins:
        - https://testbed-test-front-bucket.s3.eu-north-1.amazonaws.com
        - https://d1117tsgnqi5r8.cloudfront.net
        - https://d2kwnr7ws0sqwl.cloudfront.net
        - http://localhost:3000
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - POST

functions:
  getPopulation:
    handler: testbed.getPopulation
    events:
      - httpApi:
          path: /getPopulation
          method: post

plugins:
  - serverless-offline
