service: testbed-test-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-north-1
  httpApi:
    cors:
      allowedOrigins:
        - https://testbed-test-front-bucket.s3.eu-north-1.amazonaws.com
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - POST

functions:
  getPopulation:
    handler: testbed.getPopulation
    events:
      - httpApi:
          path: /getPopulation
          method: post

plugins:
  - serverless-offline