service: testbed-test-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ${env:AWS_REGION, 'eu-north-1'}

functions:
  getPopulation:
    handler: testbed.getPopulation
    events:
      - httpApi:
          path: /getPopulation
          method: post

plugins:
  - serverless-offline
